export const dashboardData = {
  totalStudents: 5280,
  totalTrainers: 142,
  totalAssistants: 56,
  activeCourses: 38,
  upcomingCourses: 12,
  totalRevenue: 1250000,
  pendingApprovals: 23,
  flaggedIssues: 7,
  monthlyEnrollment: [
    { month: "Jan", students: 420 },
    { month: "Feb", students: 460 },
    { month: "Mar", students: 510 },
    { month: "Apr", students: 550 },
    { month: "May", students: 590 },
    { month: "Jun", students: 620 },
  ],
  ratings: [
    { rating: 1, count: 12 },
    { rating: 2, count: 36 },
    { rating: 3, count: 120 },
    { rating: 4, count: 360 },
    { rating: 5, count: 472 },
  ],
  jobOpportunities: [
    { month: "Jan", postings: 85, applications: 320 },
    { month: "Feb", postings: 92, applications: 368 },
    { month: "Mar", postings: 108, applications: 432 },
    { month: "Apr", postings: 121, applications: 484 },
    { month: "May", postings: 135, applications: 540 },
    { month: "Jun", postings: 148, applications: 592 },
  ],
};
